/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.hmds.assessment;

import org.junit.Test;
import static org.junit.Assert.*;

public class WebServiceTest {
    //@Test public void appHasAGreeting() {
    //    WebService classUnderTest = new WebService();
    //    assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    //}
}
